### ISSUE TITLE
Some question on this project

### ISSUE THREAD

**Issue by CodeForCSharp** [YtFlow/YtFlowApp#1]
1. Is this project working now?
2. As a developer, how should I deploy this project? Because I see the code of this project scattered in different repository.

**Comment by bdbai** [comment]
1. Sure! See [Releases](https://github.com/YtFlow/YtFlowApp/releases) page for ready-to-install UWP packages and feel free to try them out.
2. As you see in this organization, every project belongs to a separate repository. To build this app, you may create a Solution in Visual Studio 2017/2019 containing all the projects. Then, manually fix the references from YtFlowApp and YtFlowTunnel so that these components can find their dependencies from correct locations. Finally, YtFlowApp would be ready to be built.

**Comment by CodeForCSharp** [comment]
Oh, I see. Thank you for your answer. In this way, it's a bit troublesome to build. If it's sub-module build, it will be good.

**Comment by bdbai** [comment]
Agree.
